name: API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  deploy_api:
    runs-on: self-hosted

    steps:
      - run: npm i
        working-directory: api
      - run: pm2 restart API
